export type CmdCategory = 'Navigation' | 'Dateien' | 'System' | 'Netzwerk' | 'Sonstiges'

export interface CmdCommand {
  id: string
  command: string
  syntax: string
  description: string
  example: string
  category: CmdCategory
  frequency: number
}

export const categoryConfig: Record<CmdCategory, { color: string; bg: string; border: string }> = {
  Navigation: {
    color: 'text-blue-700 dark:text-blue-300',
    bg: 'bg-blue-100 dark:bg-blue-900/30',
    border: 'border-blue-200 dark:border-blue-800',
  },
  Dateien: {
    color: 'text-amber-700 dark:text-amber-300',
    bg: 'bg-amber-100 dark:bg-amber-900/30',
    border: 'border-amber-200 dark:border-amber-800',
  },
  System: {
    color: 'text-red-700 dark:text-red-300',
    bg: 'bg-red-100 dark:bg-red-900/30',
    border: 'border-red-200 dark:border-red-800',
  },
  Netzwerk: {
    color: 'text-sky-700 dark:text-sky-300',
    bg: 'bg-sky-100 dark:bg-sky-900/30',
    border: 'border-sky-200 dark:border-sky-800',
  },
  Sonstiges: {
    color: 'text-violet-700 dark:text-violet-300',
    bg: 'bg-violet-100 dark:bg-violet-900/30',
    border: 'border-violet-200 dark:border-violet-800',
  },
}

export const cmdCommands: CmdCommand[] = [
  // Navigation
  {
    id: 'cd',
    command: 'cd',
    syntax: 'cd [Pfad]',
    description: 'Wechsle in ein anderes Verzeichnis',
    example: 'cd C:\\Users\\Max\\Desktop',
    category: 'Navigation',
    frequency: 10,
  },
  {
    id: 'cd-dotdot',
    command: 'cd ..',
    syntax: 'cd ..',
    description: 'Gehe ein Verzeichnis nach oben (Elternordner)',
    example: 'cd ..',
    category: 'Navigation',
    frequency: 9,
  },
  {
    id: 'dir',
    command: 'dir',
    syntax: 'dir [Pfad] [/Optionen]',
    description: 'Zeige Inhalt des aktuellen Verzeichnisses an',
    example: 'dir C:\\Users',
    category: 'Navigation',
    frequency: 10,
  },
  {
    id: 'tree',
    command: 'tree',
    syntax: 'tree [Pfad] [/F] [/A]',
    description: 'Zeige Verzeichnisstruktur als Baum an',
    example: 'tree C:\\Projekte /F',
    category: 'Navigation',
    frequency: 6,
  },
  {
    id: 'pushd',
    command: 'pushd',
    syntax: 'pushd [Pfad]',
    description: 'Speichere aktuelles Verzeichnis und wechsle zu neuem Pfad',
    example: 'pushd C:\\Windows\\System32',
    category: 'Navigation',
    frequency: 4,
  },
  {
    id: 'popd',
    command: 'popd',
    syntax: 'popd',
    description: 'Kehre zum zuletzt mit pushd gespeicherten Verzeichnis zurück',
    example: 'popd',
    category: 'Navigation',
    frequency: 4,
  },
  // Dateien
  {
    id: 'mkdir',
    command: 'mkdir',
    syntax: 'mkdir [Ordnername]',
    description: 'Erstelle einen neuen Ordner',
    example: 'mkdir MeinProjekt',
    category: 'Dateien',
    frequency: 9,
  },
  {
    id: 'rmdir',
    command: 'rmdir',
    syntax: 'rmdir [Ordner] [/S] [/Q]',
    description: 'Lösche einen Ordner (mit /S auch Inhalt)',
    example: 'rmdir AlterOrdner /S /Q',
    category: 'Dateien',
    frequency: 7,
  },
  {
    id: 'del',
    command: 'del',
    syntax: 'del [Datei] [/F] [/Q]',
    description: 'Lösche eine oder mehrere Dateien',
    example: 'del temp.txt',
    category: 'Dateien',
    frequency: 8,
  },
  {
    id: 'copy',
    command: 'copy',
    syntax: 'copy [Quelle] [Ziel]',
    description: 'Kopiere eine Datei an einen neuen Ort',
    example: 'copy bericht.pdf C:\\Backup',
    category: 'Dateien',
    frequency: 8,
  },
  {
    id: 'move',
    command: 'move',
    syntax: 'move [Quelle] [Ziel]',
    description: 'Verschiebe eine Datei oder benenne sie um',
    example: 'move alt.txt neu.txt',
    category: 'Dateien',
    frequency: 7,
  },
  {
    id: 'rename',
    command: 'rename',
    syntax: 'rename [AlterName] [NeuerName]',
    description: 'Benenne eine Datei oder einen Ordner um',
    example: 'rename entwurf.txt final.txt',
    category: 'Dateien',
    frequency: 7,
  },
  {
    id: 'type',
    command: 'type',
    syntax: 'type [Datei]',
    description: 'Zeige den Inhalt einer Textdatei im Terminal an',
    example: 'type readme.txt',
    category: 'Dateien',
    frequency: 7,
  },
  {
    id: 'attrib',
    command: 'attrib',
    syntax: 'attrib [+/-Attribut] [Datei]',
    description: 'Zeige oder ändere Dateiattribute (versteckt, schreibgeschützt)',
    example: 'attrib +h geheim.txt',
    category: 'Dateien',
    frequency: 5,
  },
  {
    id: 'xcopy',
    command: 'xcopy',
    syntax: 'xcopy [Quelle] [Ziel] [/E] [/I]',
    description: 'Kopiere Dateien und Verzeichnisstrukturen (mit Unterordnern)',
    example: 'xcopy C:\\Daten D:\\Backup /E /I',
    category: 'Dateien',
    frequency: 6,
  },
  {
    id: 'robocopy',
    command: 'robocopy',
    syntax: 'robocopy [Quelle] [Ziel] [Optionen]',
    description: 'Robustes Kopieren großer Dateimengen mit Spiegelung und Logs',
    example: 'robocopy C:\\Quell D:\\Ziel /MIR',
    category: 'Dateien',
    frequency: 5,
  },
  // System
  {
    id: 'cls',
    command: 'cls',
    syntax: 'cls',
    description: 'Leere den Terminalbildschirm (clear screen)',
    example: 'cls',
    category: 'System',
    frequency: 9,
  },
  {
    id: 'echo',
    command: 'echo',
    syntax: 'echo [Text]',
    description: 'Gib Text im Terminal aus oder schreibe ihn in eine Datei',
    example: 'echo Hallo Welt',
    category: 'System',
    frequency: 8,
  },
  {
    id: 'set',
    command: 'set',
    syntax: 'set [Variable]=[Wert]',
    description: 'Setze oder zeige Umgebungsvariablen',
    example: 'set JAVA_HOME=C:\\Java',
    category: 'System',
    frequency: 7,
  },
  {
    id: 'help',
    command: 'help',
    syntax: 'help [Befehl]',
    description: 'Zeige Hilfe zu einem CMD-Befehl an',
    example: 'help dir',
    category: 'System',
    frequency: 7,
  },
  {
    id: 'ver',
    command: 'ver',
    syntax: 'ver',
    description: 'Zeige die Windows-Version im Terminal an',
    example: 'ver',
    category: 'System',
    frequency: 6,
  },
  {
    id: 'shutdown',
    command: 'shutdown',
    syntax: 'shutdown /s /t [Sekunden]',
    description: 'Fahre den Computer nach einer bestimmten Zeit herunter',
    example: 'shutdown /s /t 60',
    category: 'System',
    frequency: 7,
  },
  {
    id: 'systeminfo',
    command: 'systeminfo',
    syntax: 'systeminfo',
    description: 'Zeige detaillierte Systeminformationen (RAM, OS, Prozessor)',
    example: 'systeminfo',
    category: 'System',
    frequency: 6,
  },
  {
    id: 'tasklist',
    command: 'tasklist',
    syntax: 'tasklist [/FI Filter]',
    description: 'Liste alle laufenden Prozesse mit PID und Speicherbedarf auf',
    example: 'tasklist /FI "IMAGENAME eq chrome.exe"',
    category: 'System',
    frequency: 7,
  },
  {
    id: 'taskkill',
    command: 'taskkill',
    syntax: 'taskkill /PID [PID] /F',
    description: 'Beende einen Prozess anhand seiner PID oder seines Namens',
    example: 'taskkill /IM notepad.exe /F',
    category: 'System',
    frequency: 7,
  },
  {
    id: 'sfc',
    command: 'sfc',
    syntax: 'sfc /scannow',
    description: 'Prüfe und repariere beschädigte Windows-Systemdateien',
    example: 'sfc /scannow',
    category: 'System',
    frequency: 6,
  },
  // Netzwerk
  {
    id: 'ipconfig',
    command: 'ipconfig',
    syntax: 'ipconfig [/all]',
    description: 'Zeige IP-Adresse, Gateway und Netzwerkinformationen an',
    example: 'ipconfig /all',
    category: 'Netzwerk',
    frequency: 9,
  },
  {
    id: 'ping',
    command: 'ping',
    syntax: 'ping [Hostname/IP]',
    description: 'Teste die Netzwerkverbindung zu einem Host',
    example: 'ping google.com',
    category: 'Netzwerk',
    frequency: 9,
  },
  {
    id: 'netstat',
    command: 'netstat',
    syntax: 'netstat [-a] [-n] [-o]',
    description: 'Zeige aktive Netzwerkverbindungen und offene Ports an',
    example: 'netstat -ano',
    category: 'Netzwerk',
    frequency: 7,
  },
  {
    id: 'tracert',
    command: 'tracert',
    syntax: 'tracert [Hostname/IP]',
    description: 'Verfolge den Netzwerkpfad zu einem Zielhost (Hops anzeigen)',
    example: 'tracert google.com',
    category: 'Netzwerk',
    frequency: 6,
  },
  // Sonstiges
  {
    id: 'find',
    command: 'find',
    syntax: 'find "[Text]" [Datei]',
    description: 'Suche nach einem Textstring in einer oder mehreren Dateien',
    example: 'find "Fehler" log.txt',
    category: 'Sonstiges',
    frequency: 7,
  },
  {
    id: 'findstr',
    command: 'findstr',
    syntax: 'findstr [/R] "[Muster]" [Datei]',
    description: 'Suche nach Text mit regulären Ausdrücken in Dateien',
    example: 'findstr /R "Error.*2024" *.log',
    category: 'Sonstiges',
    frequency: 6,
  },
  {
    id: 'path',
    command: 'path',
    syntax: 'path [Verzeichnis;...]',
    description: 'Zeige oder setze die PATH-Umgebungsvariable',
    example: 'path C:\\Java\\bin;%PATH%',
    category: 'Sonstiges',
    frequency: 5,
  },
]
